import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { AnimatePresence, motion, useMotionValue, useReducedMotion, useScroll, useSpring, useTransform } from "motion/react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUpRight, Check, ChevronDown, Mail, MapPin, Menu, Star, X } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import heroImage from "@/assets/pe-plumbing-hero.jpg";
import aboutImage from "@/assets/pe-plumbing-about.jpg";
import statementImage from "@/assets/pe-plumbing-statement.jpg";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "P&E Plumbing | Plumbing, Done Differently" },
    { name: "description", content: "Female-owned, licensed and insured plumbing in Wilkes-Barre, PA. Clean work, clear communication, and quality that lasts." },
    { property: "og:title", content: "P&E Plumbing | Plumbing, Done Differently" },
    { property: "og:description", content: "A fresh standard in plumbing for Wilkes-Barre, Pennsylvania." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: HomePage,
});

const nav = [["Home","home"],["About","about"],["Services","services"],["Why P&E","difference"],["Contact","contact"]] as const;
const serviceData = [
  ["Leak Detection & Repair","Find and fix plumbing leaks before they become bigger problems.",heroImage],
  ["Drain Cleaning","Reliable solutions for clogged and slow drains.",statementImage],
  ["Faucet & Fixture Repair","Professional repair and replacement for faucets, sinks and fixtures.",aboutImage],
  ["Toilet Repair & Replacement","Professional toilet repair, maintenance and replacement.",heroImage],
  ["Water Heater Services","Reliable water heater troubleshooting, repair and service.",statementImage],
  ["Pipe Repair","Professional solutions for damaged or leaking pipes.",statementImage],
  ["Emergency Plumbing","Fast assistance when unexpected plumbing problems happen.",heroImage],
  ["General Plumbing","Reliable plumbing support for everyday residential needs.",aboutImage],
] as const;
const reviews = [
  ["Professional, friendly and incredibly clean. Everything was explained clearly and the work was done perfectly.","Happy Customer"],
  ["Thoughtful service from start to finish. Clear expectations, careful work, and genuine respect for our home.","Local Homeowner"],
  ["Knowledgeable, responsive, and refreshingly easy to work with. The kind of service you remember.","Wilkes-Barre Resident"],
] as const;
const ease = [0.22, 1, 0.36, 1] as const;
const reveal = { initial:{opacity:0,y:45}, whileInView:{opacity:1,y:0}, viewport:{once:true,margin:"-12%"}, transition:{duration:.8,ease} };

function MagneticLink({ children, onClick, className="" }: { children: React.ReactNode; onClick?:()=>void; className?:string }) {
  const x=useMotionValue(0), y=useMotionValue(0); const sx=useSpring(x,{stiffness:180,damping:18}), sy=useSpring(y,{stiffness:180,damping:18});
  return <motion.button style={{x:sx,y:sy}} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)*.14);y.set((e.clientY-r.top-r.height/2)*.14)}} onMouseLeave={()=>{x.set(0);y.set(0)}} whileTap={{scale:.97}} onClick={onClick} className={`group relative overflow-hidden rounded-full ${className}`}>{children}<span className="absolute inset-y-0 -left-1/3 w-1/4 -skew-x-12 bg-hero-foreground/25 opacity-0 group-hover:animate-shine group-hover:opacity-100"/></motion.button>;
}

function Eyebrow({children,dark=false}:{children:React.ReactNode;dark?:boolean}) { return <p className={`flex items-center gap-3 text-[10px] font-bold uppercase tracking-[.3em] ${dark?"text-copper":"text-copper-emphasis"}`}><span className="h-px w-8 bg-current"/>{children}</p> }

function CustomCursor({label}:{label:string}) {
  const x=useMotionValue(-100),y=useMotionValue(-100); const sx=useSpring(x,{stiffness:700,damping:45}),sy=useSpring(y,{stiffness:700,damping:45});
  useEffect(()=>{const move=(e:MouseEvent)=>{x.set(e.clientX);y.set(e.clientY)};window.addEventListener("mousemove",move);return()=>window.removeEventListener("mousemove",move)},[x,y]);
  return <motion.div aria-hidden style={{x:sx,y:sy}} className={`pointer-events-none fixed left-0 top-0 z-[100] hidden -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full border border-copper bg-primary/85 text-[9px] font-bold uppercase tracking-widest text-hero-foreground backdrop-blur-md lg:flex ${label?"size-20":"size-3"}`}>{label}</motion.div>;
}

function HomePage(){
  const [scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false),[active,setActive]=useState("home"),[service,setService]=useState(0),[review,setReview]=useState(0),[cursor,setCursor]=useState("");
  const reduce=useReducedMotion(); const heroRef=useRef<HTMLElement>(null); const {scrollYProgress}=useScroll({target:heroRef,offset:["start start","end start"]}); const heroY=useTransform(scrollYProgress,[0,1],[0,120]);
  useEffect(()=>{const fn=()=>{setScrolled(window.scrollY>40);const current=[...nav].reverse().find(([,id])=>{const el=document.getElementById(id);return el?el.getBoundingClientRect().top<180:false});if(current)setActive(current[1])};fn();window.addEventListener("scroll",fn,{passive:true});return()=>window.removeEventListener("scroll",fn)},[]);
  const go=(id:string)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=new FormData(e.currentTarget);window.location.href=`mailto:peplumbingnepa@gmail.com?subject=${encodeURIComponent(`Estimate request: ${d.get("service")}`)}&body=${encodeURIComponent(`Name: ${d.get("name")}\nEmail: ${d.get("email")}\nPhone: ${d.get("phone")}\nService: ${d.get("service")}\n\n${d.get("message")}`)}`};
  const currentService=serviceData[service] ?? serviceData[0]; const currentReview=reviews[review] ?? reviews[0];
  const marquee=useMemo(()=>Array(2).fill(["CLEAN WORK","CLEAR COMMUNICATION","QUALITY THAT LASTS","FEMALE OWNED","LICENSED & INSURED"]).flat(),[]);

  return <main className="bg-background text-foreground lg:cursor-none"><CustomCursor label={cursor}/>
    <header className={`fixed left-1/2 top-4 z-50 w-[calc(100%-24px)] max-w-6xl -translate-x-1/2 rounded-full border transition-all duration-500 ${scrolled?"border-hero-foreground/20 bg-primary/90 px-3 py-2 shadow-2xl backdrop-blur-2xl":"border-hero-foreground/15 bg-primary/35 px-4 py-3 backdrop-blur-xl"}`}>
      <div className="flex items-center justify-between"><button onClick={()=>go("home")} className="flex items-center gap-3 text-hero-foreground"><span className="flex size-9 items-center justify-center rounded-full border border-copper/60 font-display text-xs italic text-copper">P&E</span><span className="font-display text-lg font-semibold">P&E Plumbing</span></button>
      <nav className="hidden items-center gap-1 rounded-full border border-hero-foreground/10 bg-hero-foreground/5 p-1 lg:flex">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)} className={`relative rounded-full px-4 py-2 text-xs transition-all duration-300 ${active===id?"bg-hero-foreground/12 text-hero-foreground":"text-hero-foreground/60 hover:text-hero-foreground"}`}>{l}</button>)}</nav>
      <MagneticLink onClick={()=>go("contact")} className="hidden bg-copper px-5 py-3 text-xs font-bold text-copper-foreground lg:block">Get a Free Estimate <ArrowUpRight className="ml-2 inline size-3 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></MagneticLink>
      <button aria-label={menu?"Close menu":"Open menu"} onClick={()=>setMenu(!menu)} className="flex size-10 items-center justify-center rounded-full text-hero-foreground lg:hidden">{menu?<X/>:<Menu/>}</button></div>
    </header>
    <AnimatePresence>{menu&&<motion.div initial={{clipPath:"circle(0% at 90% 5%)"}} animate={{clipPath:"circle(150% at 90% 5%)"}} exit={{clipPath:"circle(0% at 90% 5%)"}} transition={{duration:.65,ease}} className="fixed inset-0 z-40 flex flex-col justify-center bg-primary px-7 text-hero-foreground lg:hidden">{nav.map(([l,id],i)=><motion.button initial={{opacity:0,x:-25}} animate={{opacity:1,x:0}} transition={{delay:.15+i*.06}} key={id} onClick={()=>go(id)} className="border-b border-hero-foreground/15 py-5 text-left font-display text-4xl italic">{l}</motion.button>)}<a href="mailto:peplumbingnepa@gmail.com" className="mt-10 text-sm text-copper">peplumbingnepa@gmail.com</a></motion.div>}</AnimatePresence>

    <section ref={heroRef} id="home" className="grain relative min-h-[100svh] overflow-hidden bg-primary"><motion.img style={{y:reduce?0:heroY}} src={heroImage} alt="P&E Plumbing professional working in a modern home" width={1920} height={1200} fetchPriority="high" className="absolute inset-0 size-full scale-110 object-cover object-[64%_center] opacity-70"/><div className="absolute inset-0 bg-gradient-to-r from-primary via-primary/80 to-primary/20"/><div className="absolute inset-0 bg-gradient-to-t from-primary via-transparent to-primary/30"/>
      <div className="relative z-10 mx-auto flex min-h-[100svh] max-w-[1440px] items-end px-5 pb-20 pt-32 sm:px-9 lg:px-14 lg:pb-16"><div className="grid w-full items-end gap-10 lg:grid-cols-12">
        <div className="lg:col-span-9"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{delay:.35,duration:.8}}><Eyebrow dark>Female-owned • Wilkes-Barre, PA</Eyebrow></motion.div><h1 className="mt-6 font-display text-[clamp(3.8rem,9.5vw,9.5rem)] font-semibold uppercase leading-[.78] text-hero-foreground"><motion.span initial={{y:"100%"}} animate={{y:0}} transition={{duration:1,ease}} className="block">Plumbing,</motion.span><motion.span initial={{opacity:0,x:55}} animate={{opacity:1,x:0}} transition={{delay:.2,duration:1,ease}} className="ml-[7vw] block bg-gradient-to-r from-copper via-ivory-deep to-copper bg-clip-text italic text-transparent">Done Differently.</motion.span></h1>
          <div className="mt-9 flex max-w-3xl flex-col gap-7 border-t border-hero-foreground/20 pt-7 md:flex-row md:items-center md:justify-between"><p className="max-w-md text-sm leading-6 text-hero-foreground/65">Female-owned. Licensed. Insured.<br/>Clean work. Clear communication. Quality that lasts.</p><div className="flex flex-wrap items-center gap-5"><MagneticLink onClick={()=>go("contact")} className="bg-copper px-6 py-4 text-xs font-bold uppercase tracking-widest text-copper-foreground">Get a Free Estimate <ArrowUpRight className="ml-2 inline size-4"/></MagneticLink><button onClick={()=>go("services")} className="group flex items-center gap-3 text-xs font-bold uppercase tracking-widest text-hero-foreground">Explore Services <ArrowDown className="size-4 transition-transform group-hover:translate-y-1"/></button></div></div>
        </div>
        <div className="hidden border-l border-hero-foreground/15 pl-8 lg:col-span-3 lg:block"><p className="text-[10px] uppercase tracking-[.3em] text-hero-foreground/35">The P&E Standard</p>{[["01","Licensed & Insured"],["02","Quality First"],["03","Local Service"]].map(([n,t])=><div key={n} className="flex items-center gap-4 border-b border-hero-foreground/10 py-5"><span className="text-xs text-copper">{n}</span><span className="font-display text-xl italic text-hero-foreground">{t}</span></div>)}</div>
      </div></div>
      <motion.div animate={{y:[0,-8,0]}} transition={{duration:5,repeat:Infinity}} className="absolute right-8 top-[24%] z-20 hidden rounded-md border border-hero-foreground/20 bg-primary/55 p-4 text-hero-foreground shadow-2xl backdrop-blur-xl xl:block"><p className="text-[9px] uppercase tracking-[.25em] text-copper">Licensed & Insured</p><p className="mt-2 flex items-center gap-2 text-sm"><Check className="size-3"/> Professional Service</p></motion.div>
      <div className="absolute bottom-5 left-1/2 z-20 hidden -translate-x-1/2 flex-col items-center gap-2 text-[8px] uppercase tracking-[.3em] text-hero-foreground/40 md:flex">Scroll to explore<span className="h-10 w-px origin-top bg-copper animate-line-drop"/></div>
    </section>

    <section className="overflow-hidden bg-primary py-5 text-hero-foreground"><div className="flex w-max animate-marquee">{marquee.map((item,i)=><div key={`${item}-${i}`} className="flex items-center whitespace-nowrap px-5 text-xs uppercase tracking-[.24em]"><span>{item}</span><span className="ml-10 text-copper">✦</span></div>)}</div></section>

    <section id="about" className="relative scroll-mt-20 overflow-hidden py-24 lg:py-36"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-12 lg:grid-cols-12">
      <motion.div {...reveal} className="relative z-10 lg:col-span-7"><Eyebrow>About P&E</Eyebrow><h2 className="mt-7 text-[clamp(4rem,9vw,8rem)] font-semibold uppercase leading-[.78] text-primary">A Fresh<br/><span className="ml-[9vw] italic text-copper-emphasis">Standard</span><br/>In Plumbing.</h2><p className="ml-auto mt-10 max-w-md text-base leading-8 text-muted-foreground">P&E Plumbing is built around a simple idea: plumbing service should be professional, transparent, clean, and dependable.</p></motion.div>
      <div className="relative min-h-[640px] lg:col-span-5"><motion.img {...reveal} src={aboutImage} alt="Female plumber installing a premium fixture" width={1200} height={1408} loading="lazy" className="absolute right-0 top-0 h-[82%] w-[88%] rounded-sm object-cover shadow-2xl"/><motion.img initial={{opacity:0,y:70}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{duration:1,ease}} src={statementImage} alt="Detailed copper plumbing craftsmanship" width={1920} height={1088} loading="lazy" className="absolute bottom-0 left-0 h-56 w-[58%] rounded-sm border-8 border-background object-cover shadow-2xl"/><div className="absolute right-4 top-[70%] rounded-full border border-copper bg-background px-5 py-3 text-[10px] font-bold uppercase tracking-widest text-copper-emphasis shadow-xl">Female-Owned Business</div></div>
    </div><div className="mt-20 grid border-y border-border md:grid-cols-3">{["Skilled workmanship","Clear communication","Genuine customer care"].map((t,i)=><div key={t} className="flex items-center gap-5 border-b border-border py-7 md:border-b-0 md:border-r md:px-8 md:first:pl-0 md:last:border-0"><span className="font-display text-4xl italic text-copper">0{i+1}</span><p className="text-sm font-bold uppercase tracking-wider">{t}</p></div>)}</div></div></section>

    <section id="difference" className="scroll-mt-20 bg-primary py-24 text-hero-foreground lg:py-36"><div className="mx-auto max-w-7xl px-5 lg:px-10"><Eyebrow dark>The P&E Difference</Eyebrow><motion.h2 {...reveal} className="mt-8 max-w-5xl text-4xl leading-tight sm:text-6xl lg:text-7xl">Plumbing should feel simple.<br/><span className="italic text-copper">Your experience shouldn’t feel stressful.</span></motion.h2><div className="mt-16 grid border-y border-hero-foreground/15 lg:grid-cols-4">{["Clean Work","Clear Communication","Quality That Lasts","Customer First"].map((t,i)=><motion.div onMouseEnter={()=>setCursor("View")} onMouseLeave={()=>setCursor("")} whileHover={{y:-10}} key={t} className="group min-h-64 border-b border-hero-foreground/15 p-7 transition-colors hover:bg-hero-foreground/5 lg:border-b-0 lg:border-r lg:last:border-0"><span className="font-display text-5xl italic text-copper/45 transition-all duration-500 group-hover:text-7xl group-hover:text-copper">0{i+1}</span><div className="mt-24 flex items-end justify-between"><h3 className="font-display text-2xl italic">{t}</h3><ArrowUpRight className="size-5 translate-y-2 opacity-0 transition-all group-hover:translate-y-0 group-hover:opacity-100"/></div></motion.div>)}</div></div></section>

    <section id="services" className="scroll-mt-20 py-24 lg:py-36"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-12 lg:grid-cols-12"><div className="lg:col-span-7"><Eyebrow>What We Do</Eyebrow><div className="mt-9 border-t border-foreground/20">{serviceData.map(([title,text],i)=><div key={title} onMouseEnter={()=>{setService(i);setCursor("Explore")}} onMouseLeave={()=>setCursor("")} className="group border-b border-foreground/20"><button onClick={()=>setService(service===i?-1:i)} className="flex w-full items-center gap-4 py-5 text-left"><span className="text-xs text-copper-emphasis">{String(i+1).padStart(2,"0")}</span><h3 className={`flex-1 font-display text-2xl italic transition-all sm:text-3xl ${service===i?"translate-x-3 text-copper-emphasis":"text-primary group-hover:translate-x-2"}`}>{title}</h3><ArrowUpRight className={`size-5 transition-all ${service===i?"rotate-0 opacity-100":"rotate-45 opacity-25"}`}/></button><AnimatePresence>{service===i&&<motion.p initial={{height:0,opacity:0}} animate={{height:"auto",opacity:1}} exit={{height:0,opacity:0}} className="overflow-hidden pb-5 pl-10 text-sm leading-6 text-muted-foreground lg:hidden">{text}</motion.p>}</AnimatePresence></div>)}</div></div>
        <div className="sticky top-28 hidden h-[650px] overflow-hidden rounded-sm bg-primary lg:col-span-5 lg:block" onMouseEnter={()=>setCursor("Explore")} onMouseLeave={()=>setCursor("")}><AnimatePresence mode="wait"><motion.img key={service} initial={{opacity:0,scale:1.08}} animate={{opacity:1,scale:1}} exit={{opacity:0}} transition={{duration:.6,ease}} src={currentService?.[2]} alt={currentService?.[0] ?? "P&E Plumbing service"} width={1200} height={1408} loading="lazy" className="size-full object-cover"/></AnimatePresence><div className="absolute inset-0 bg-gradient-to-t from-primary/85 to-transparent"/><div className="absolute bottom-8 left-8 right-8"><p className="text-[10px] uppercase tracking-[.3em] text-copper">Selected Service</p><p className="mt-3 max-w-sm text-sm leading-6 text-hero-foreground/70">{currentService?.[1]}</p></div></div>
      </div></div></section>

    <section className="grain relative min-h-[90vh] overflow-hidden bg-primary"><motion.img initial={{scale:1.12}} whileInView={{scale:1}} viewport={{once:true}} transition={{duration:1.8,ease}} src={statementImage} alt="Copper plumbing illuminated in a dark architectural space" width={1920} height={1088} loading="lazy" className="absolute inset-0 size-full object-cover opacity-45"/><div className="absolute inset-0 bg-primary/45"/><motion.div {...reveal} className="relative z-10 flex min-h-[90vh] flex-col items-center justify-center px-5 text-center"><p className="mb-8 text-[10px] uppercase tracking-[.35em] text-copper">The promise</p><h2 className="text-[clamp(3.5rem,8vw,8rem)] font-semibold uppercase leading-[.82] text-hero-foreground">Good Plumbing<br/>Shouldn’t Be<br/><span className="bg-gradient-to-r from-copper via-ivory-deep to-copper bg-clip-text italic text-transparent">Complicated.</span></h2></motion.div></section>

    <section className="py-24 lg:py-36"><div className="mx-auto max-w-7xl px-5 lg:px-10"><Eyebrow>How It Works</Eyebrow><motion.h2 {...reveal} className="mt-7 text-5xl text-primary sm:text-7xl">From problem to <span className="italic text-copper-emphasis">peace of mind.</span></motion.h2><div className="relative mt-20 grid gap-0 md:grid-cols-4"><motion.div initial={{scaleX:0}} whileInView={{scaleX:1}} viewport={{once:true}} transition={{duration:1.4,ease}} className="absolute left-0 right-0 top-7 hidden h-px origin-left bg-copper md:block"/>{[["Tell Us What’s Wrong","Share the issue and what you’re experiencing."],["Get a Clear Estimate","We discuss the work and pricing transparently."],["We Do the Work","Careful, professional service in your home."],["Enjoy the Result","Dependable quality you can feel confident in."]].map(([t,d],i)=><motion.div {...reveal} transition={{duration:.7,delay:i*.12}} key={t} className="relative border-l border-border pb-12 pl-8 md:border-0 md:pb-0 md:pl-0 md:pr-10"><span className="relative z-10 -ml-[49px] flex size-14 items-center justify-center rounded-full border border-copper bg-background font-display text-lg italic text-copper-emphasis md:ml-0">0{i+1}</span><h3 className="mt-7 text-2xl italic text-primary">{t}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{d}</p></motion.div>)}</div></div></section>

    <section className="bg-primary py-24 text-hero-foreground lg:py-32"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-14 lg:grid-cols-2"><motion.h2 {...reveal} className="text-6xl uppercase leading-[.85] sm:text-8xl">Built On <span className="italic text-copper">Trust.</span><br/>Backed By Quality.</motion.h2><div className="grid grid-cols-2 border border-hero-foreground/15">{["Licensed","Insured","Female-Owned","Customer-Focused"].map((t,i)=><motion.div {...reveal} key={t} className="group min-h-40 border-b border-r border-hero-foreground/15 p-6 last:border-b-0 even:border-r-0"><span className="text-xs text-copper">0{i+1}</span><p className="mt-14 text-xs font-bold uppercase tracking-[.15em] text-hero-foreground/75 group-hover:text-hero-foreground">{t}</p></motion.div>)}</div></div></div></section>

    <section className="overflow-hidden py-24 lg:py-36"><div className="mx-auto max-w-6xl px-5 lg:px-10"><div className="flex items-end justify-between"><div><Eyebrow>Kind Words</Eyebrow><h2 className="mt-7 text-5xl sm:text-7xl">The experience<br/><span className="italic text-copper-emphasis">we aim for.</span></h2></div><div className="hidden gap-2 sm:flex"><button aria-label="Previous testimonial" onClick={()=>setReview((review+reviews.length-1)%reviews.length)} className="flex size-12 items-center justify-center rounded-full border border-border hover:border-copper"><ArrowLeft/></button><button aria-label="Next testimonial" onClick={()=>setReview((review+1)%reviews.length)} className="flex size-12 items-center justify-center rounded-full border border-border hover:border-copper"><ArrowRight/></button></div></div><p className="mt-6 text-xs text-muted-foreground">Placeholder testimonials — replace with verified customer reviews before publishing.</p>
      <motion.div key={review} drag="x" dragConstraints={{left:0,right:0}} onDragEnd={(_,info)=>{if(info.offset.x<-50)setReview((review+1)%reviews.length);if(info.offset.x>50)setReview((review+reviews.length-1)%reviews.length)}} initial={{opacity:0,x:55}} animate={{opacity:1,x:0}} className="relative mt-12 cursor-grab border-y border-border py-14 active:cursor-grabbing"><span className="absolute -top-4 left-0 font-display text-9xl text-copper/20">“</span><div className="relative grid gap-8 md:grid-cols-[.3fr_1fr]"><div className="flex gap-1 text-copper">{Array.from({length:5}).map((_,i)=><Star key={i} className="size-4 fill-current"/>)}</div><div><blockquote className="font-display text-3xl italic leading-snug text-primary sm:text-5xl">“{currentReview?.[0]}”</blockquote><p className="mt-7 text-xs font-bold uppercase tracking-[.2em] text-copper-emphasis">— {currentReview?.[1]}</p></div></div></motion.div><div className="mt-6 flex items-center gap-3"><span className="text-xs text-muted-foreground">0{review+1}</span><div className="h-px flex-1 bg-border"><motion.div animate={{width:`${((review+1)/reviews.length)*100}%`}} className="h-px bg-copper"/></div><span className="text-xs text-muted-foreground">0{reviews.length}</span></div></div></section>

    <section className="relative min-h-[75vh] overflow-hidden bg-primary text-hero-foreground"><div className="absolute inset-0 opacity-20 [background-image:linear-gradient(var(--color-hero-foreground)_1px,transparent_1px),linear-gradient(90deg,var(--color-hero-foreground)_1px,transparent_1px)] [background-size:64px_64px]"/><div className="absolute left-[68%] top-[42%] size-64 -translate-x-1/2 -translate-y-1/2 rounded-full bg-copper/15 blur-3xl"/><div className="relative z-10 mx-auto grid min-h-[75vh] max-w-7xl items-center gap-12 px-5 py-24 lg:grid-cols-2 lg:px-10"><motion.div {...reveal}><Eyebrow dark>Service Area</Eyebrow><h2 className="mt-8 text-6xl uppercase leading-[.85] sm:text-8xl">Proudly Serving<br/><span className="italic text-copper">Wilkes-Barre, PA</span></h2><a href="https://www.google.com/maps/search/?api=1&query=Wilkes-Barre%2C+PA+18705" target="_blank" rel="noreferrer" className="mt-8 inline-block text-sm text-hero-foreground/60 hover:text-copper">Wilkes-Barre, PA, United States, 18705</a></motion.div><motion.a {...reveal} href="https://www.google.com/maps/dir/?api=1&destination=Wilkes-Barre%2C+PA+18705" target="_blank" rel="noreferrer" className="group relative mx-auto flex aspect-square w-full max-w-md items-center justify-center rounded-full border border-hero-foreground/15 bg-hero-foreground/5 backdrop-blur-xl"><span className="absolute inset-[12%] rounded-full border border-hero-foreground/10"/><span className="absolute inset-[27%] rounded-full border border-copper/40"/><span className="flex size-20 items-center justify-center rounded-full bg-copper text-copper-foreground shadow-copper-lg transition-transform group-hover:scale-110"><MapPin/></span><span className="absolute bottom-[18%] text-[10px] uppercase tracking-[.25em]">Get Directions ↗</span></motion.a></div></section>

    <section id="contact" className="grain relative scroll-mt-16 overflow-hidden bg-primary py-24 text-hero-foreground lg:py-36"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-16 lg:grid-cols-12"><div className="lg:col-span-7"><Eyebrow dark>Start a Conversation</Eyebrow><motion.h2 {...reveal} className="mt-8 text-[clamp(4.5rem,9vw,9rem)] uppercase leading-[.78]">Let’s Fix<br/><span className="italic text-copper">What’s Broken.</span></motion.h2><p className="mt-8 max-w-md text-lg text-hero-foreground/60">Have a plumbing issue or need a professional estimate? Let’s talk.</p><MagneticLink onClick={()=>document.getElementById("estimate-form")?.scrollIntoView({behavior:"smooth"})} className="mt-10 bg-copper px-8 py-5 text-sm font-bold uppercase tracking-wider text-copper-foreground">Get a Free Estimate <ArrowUpRight className="ml-3 inline size-4"/></MagneticLink><div className="mt-12 space-y-3 text-sm text-hero-foreground/55"><a href="mailto:peplumbingnepa@gmail.com" className="flex items-center gap-3 hover:text-copper"><Mail className="size-4"/>peplumbingnepa@gmail.com</a><p className="flex items-center gap-3"><MapPin className="size-4"/>Wilkes-Barre, PA, United States, 18705</p></div></div>
        <motion.form id="estimate-form" {...reveal} onSubmit={submit} className="rounded-sm border border-hero-foreground/15 bg-hero-foreground/5 p-6 shadow-2xl backdrop-blur-xl sm:p-9 lg:col-span-5"><p className="font-display text-2xl italic">Tell us what’s happening.</p><div className="mt-8 space-y-5">{[["name","Full Name","text"],["email","Email","email"],["phone","Phone","tel"]].map(([n,l,t])=><label key={n} className="block text-[10px] uppercase tracking-[.2em] text-hero-foreground/50">{l}<Input required name={n} type={t} className="mt-2 h-12 rounded-none border-x-0 border-t-0 border-hero-foreground/20 bg-transparent px-0 text-hero-foreground placeholder:text-hero-foreground/25 focus-visible:ring-0 focus-visible:border-copper"/></label>)}<label className="block text-[10px] uppercase tracking-[.2em] text-hero-foreground/50">Service Needed<select required name="service" defaultValue="" className="mt-2 h-12 w-full border-x-0 border-t-0 border-b border-hero-foreground/20 bg-transparent text-sm text-hero-foreground outline-none focus:border-copper"><option value="" disabled className="bg-primary">Choose a service</option>{serviceData.map(([t])=><option key={t} className="bg-primary">{t}</option>)}</select></label><label className="block text-[10px] uppercase tracking-[.2em] text-hero-foreground/50">Message<Textarea required name="message" className="mt-2 min-h-24 rounded-none border-x-0 border-t-0 border-hero-foreground/20 bg-transparent px-0 text-hero-foreground focus-visible:ring-0 focus-visible:border-copper"/></label></div><button type="submit" className="mt-8 flex w-full items-center justify-between rounded-full bg-copper px-6 py-4 text-xs font-bold uppercase tracking-wider text-copper-foreground transition-transform hover:scale-[1.02]">Request Estimate <ArrowUpRight className="size-4"/></button></motion.form>
      </div></div></section>

    <footer className="bg-primary px-5 pb-8 text-hero-foreground lg:px-10"><div className="mx-auto max-w-7xl border-t border-hero-foreground/15 pt-16"><p className="font-display text-[clamp(7rem,19vw,18rem)] leading-[.7] text-hero-foreground/90">P&E</p><div className="mt-16 grid gap-10 border-t border-hero-foreground/15 pt-10 md:grid-cols-3"><div><p className="font-display text-2xl italic">P&E Plumbing</p><p className="mt-3 text-sm text-hero-foreground/45">Clean Work. Clear Communication.<br/>Quality That Lasts.</p></div><nav className="grid grid-cols-2 gap-3 text-xs uppercase tracking-wider text-hero-foreground/55">{nav.map(([l,id])=><button key={id} onClick={()=>go(id)} className="text-left hover:text-copper">{l}</button>)}</nav><div className="text-sm leading-7 text-hero-foreground/45"><p>Wilkes-Barre, PA 18705</p><a href="mailto:peplumbingnepa@gmail.com" className="hover:text-copper">peplumbingnepa@gmail.com</a></div></div><div className="mt-12 flex items-center justify-between border-t border-hero-foreground/10 pt-7 text-[10px] uppercase tracking-wider text-hero-foreground/30"><p>© 2026 P&E Plumbing</p><button onClick={()=>go("home")} className="flex items-center gap-2 hover:text-copper">Back to top <ArrowUpRight className="size-3 -rotate-45"/></button></div></div></footer>
  </main>
}